version: 2.1

executors:
  buildpack:
    docker:
      - image: cimg/node:16.20.2
    working_directory: ~/repo

jobs:
  build-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: NPM Install
          command: npm ci
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Build docker image
          command: docker build -t chatpad .

  publish-latest-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: NPM Install
          command: npm ci
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Build docker image
          command: |
            docker build -t "aegirops/chatpad:latest" -t "aegirops/chatpad:${CIRCLE_TAG}" . --no-cache
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aegirops/chatpad:latest
            docker push aegirops/chatpad:${CIRCLE_TAG}

workflows:
  build-test:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - /.*/

  publish:
    jobs:
      - publish-latest-docker-image:
          context: dockerGcloudCli
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
